### ISSUE TITLE
On a clean install, you are allowed to press the buttons

### ISSUE THREAD

**Issue by Smurf-IV** [BlueBlock/Elucidate#16]
I do not have Snapraid installed, 
Or, it is installed to a different location.
This does not cause a crash report, but just a messageBox

**Comment by Smurf-IV** [comment]
Thanks for checking for the existence of the log file, Now you have to check the existence of the snapRaid.exe !

**Comment by Smurf-IV** [comment]
![image](https://user-images.githubusercontent.com/2418812/46304955-ec54f080-c5a7-11e8-906a-9926a75c0fb5.png)

**Comment by Smurf-IV** [comment]
```
2018-10-01 18:28:33.8916[7] INFO Elucidate.Logging.Log: Using: c:\SnapRAID\SnapRAID.exe 
2018-10-01 18:28:33.9076[7] INFO Elucidate.Logging.Log: with:  -c "D:\SnapRaid\SnapRaid - Copy.Conf" sync  
2018-10-01 18:28:34.0306[7] FATAL Elucidate.Logging.Log: Thread closing abnormally System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Elucidate.Controls.LiveRunLogControl.RunSnapRaid(DoWorkEventArgs e, String args, String appPath, BackgroundWorker worker)
   at Elucidate.Controls.LiveRunLogControl.actionWorker_DoWork(Object sender, DoWorkEventArgs e)
2018-10-01 18:29:44.1005[1] ERROR Elucidate.Logging.Log: Thread threw:  System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Elucidate.Controls.LiveRunLogControl.RunSnapRaid(DoWorkEventArgs e, String args, String appPath, BackgroundWorker worker)
   at Elucidate.Controls.LiveRunLogControl.actionWorker_DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

```
